.TH rbright 1 rbright\-0.1
.SH NAME
rbright \- Change screen brightness, print to stdout and signal program.
.SH SYNOPSIS
.B rbright
.RB [ \-+hp ] <program>
.SH DESCRIPTION
rbright is a program to change the screen brightness and print the current value of brightness to stdout,
and optionally signal another program.
.P
To do so, it has to read and write the corresponding file.
Please note, that in order to do this you must have the right permissions.
.SH USAGE
.TP
.BI "\-"
Decrease screen brightness, and then print to stdout.
.TP
.B "+"
Increase screen brightness, and then print to stdout.
.TP
.BI "h"
Print usage, and then print to stdout.
.TP
.BI "p"
Print current brightness.
.TP
.B
Without arguments, also print current brightness.
.TP
.BI "<program>"
If <program> is set, rbright will send $BRIGHT signal do the program named <program>.
.SH ENVIRONMENT VARIABLES
.TP
.BI "$BRIGHT"
Which signal number should be send to <program>
.SH AUTHOR
.EX
Lucas Mior   <lucas.mior at tutamail.com>
.EE
.SH SEE ALSO
.BR X (7),
.BR xrdb (1)
